
[build]
  command = "npm run build"
  publish = "dist"

# Ensure Netlify uses the latest Node version
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional --legacy-peer-deps --ignore-scripts"

# Remove the NextJS plugin since this is a Vite project, not Next.js
# [[plugins]]
#  package = "@netlify/plugin-nextjs"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
